import { Cormorant_Upright, DM_Sans, Finger_Paint } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/utils/nav/Navbar";

const cormorant_Upright = Finger_Paint({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-cormorant_upright",
});

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-dm_sans",
});

export const metadata = {
  title: "Talha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/T.svg" />
      </head>
      <body className={`${cormorant_Upright.variable} ${dm_sans.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
